### ISSUE TITLE
Missing package.json

### ISSUE THREAD

**Issue by cocowalla** [OutSystems/cordova-plugin-audiorecorder#1]
A `package.json` file is [required](https://github.com/Telerik-Verified-Plugins/ImagePicker/issues/55) to allow plugins to be added from Github when using Cordova 7.x.

Would appreciate it if you could add one.

**Comment by Chuckytuh** [comment]
Hi @cocowalla , a PR would be more than appreciated if you're willing to do it. 

Cheers

**Comment by cocowalla** [comment]
Have you had a chance to look at the PR yet?
